export const locationsDatabase = [
  // Major Chinese Cities
  {
    name: "北京",
    nameEn: "Beijing",
    nameAr: "بكين",
    nameMs: "Beijing",
    namePt: "Pequim",
    nameEs: "Pekín",
    lat: 39.9042,
    lng: 116.4074,
    type: "city",
    address: "中国首都 | Capital of China | عاصمة الصين",
  },
  {
    name: "上海",
    nameEn: "Shanghai",
    nameAr: "شانغهاي",
    nameMs: "Shanghai",
    namePt: "Xangai",
    nameEs: "Shanghái",
    lat: 31.2304,
    lng: 121.4737,
    type: "city",
    address: "中国最大城市 | Largest city in China | أكبر مدينة في الصين",
  },
  {
    name: "广州",
    nameEn: "Guangzhou",
    nameAr: "قوانغتشو",
    nameMs: "Guangzhou",
    namePt: "Cantão",
    nameEs: "Cantón",
    lat: 23.1291,
    lng: 113.2644,
    type: "city",
    address: "广东省会 | Capital of Guangdong | عاصمة قوانغدونغ",
  },
  {
    name: "深圳",
    nameEn: "Shenzhen",
    nameAr: "شنتشن",
    nameMs: "Shenzhen",
    namePt: "Shenzhen",
    nameEs: "Shenzhen",
    lat: 22.5431,
    lng: 114.0579,
    type: "city",
    address: "科技创新城市 | Tech innovation city | مدينة الابتكار التقني",
  },
  {
    name: "成都",
    nameEn: "Chengdu",
    nameAr: "تشنغدو",
    nameMs: "Chengdu",
    namePt: "Chengdu",
    nameEs: "Chengdu",
    lat: 30.5728,
    lng: 104.0668,
    type: "city",
    address: "四川省会 | Capital of Sichuan | عاصمة سيتشوان",
  },
  {
    name: "杭州",
    nameEn: "Hangzhou",
    nameAr: "هانغتشو",
    nameMs: "Hangzhou",
    namePt: "Hangzhou",
    nameEs: "Hangzhou",
    lat: 30.2741,
    lng: 120.1551,
    type: "city",
    address: "浙江省会 | Capital of Zhejiang | عاصمة تشجيانغ",
  },
  {
    name: "西安",
    nameEn: "Xi'an",
    nameAr: "شيان",
    nameMs: "Xi'an",
    namePt: "Xi'an",
    nameEs: "Xi'an",
    lat: 34.2667,
    lng: 108.9,
    type: "city",
    address: "陕西省会 | Capital of Shaanxi | عاصمة شنشي",
  },
  {
    name: "重庆",
    nameEn: "Chongqing",
    nameAr: "تشونغتشينغ",
    nameMs: "Chongqing",
    namePt: "Chongqing",
    nameEs: "Chongqing",
    lat: 29.563,
    lng: 106.5516,
    type: "city",
    address: "直辖市 | Municipality | بلدية",
  },
  {
    name: "武汉",
    nameEn: "Wuhan",
    nameAr: "ووهان",
    nameMs: "Wuhan",
    namePt: "Wuhan",
    nameEs: "Wuhan",
    lat: 30.5928,
    lng: 114.3055,
    type: "city",
    address: "湖北省会 | Capital of Hubei | عاصمة هوبي",
  },
  {
    name: "天津",
    nameEn: "Tianjin",
    nameAr: "تيانجين",
    nameMs: "Tianjin",
    namePt: "Tianjin",
    nameEs: "Tianjin",
    lat: 39.1422,
    lng: 117.1767,
    type: "city",
    address: "直辖市 | Municipality | بلدية",
  },
  {
    name: "南京",
    nameEn: "Nanjing",
    nameAr: "نانجينغ",
    nameMs: "Nanjing",
    namePt: "Nanquim",
    nameEs: "Nankín",
    lat: 32.0603,
    lng: 118.7969,
    type: "city",
    address: "江苏省会 | Capital of Jiangsu | عاصمة جيانغسو",
  },
  {
    name: "苏州",
    nameEn: "Suzhou",
    nameAr: "سوتشو",
    nameMs: "Suzhou",
    namePt: "Suzhou",
    nameEs: "Suzhou",
    lat: 31.2989,
    lng: 120.5853,
    type: "city",
    address: "江苏省 | Jiangsu Province | مقاطعة جيانغسو",
  },
  {
    name: "青岛",
    nameEn: "Qingdao",
    nameAr: "تشينغداو",
    nameMs: "Qingdao",
    namePt: "Qingdao",
    nameEs: "Qingdao",
    lat: 36.0671,
    lng: 120.3826,
    type: "city",
    address: "山东省 | Shandong Province | مقاطعة شاندونغ",
  },
  {
    name: "大连",
    nameEn: "Dalian",
    nameAr: "داليان",
    nameMs: "Dalian",
    namePt: "Dalian",
    nameEs: "Dalian",
    lat: 38.914,
    lng: 121.6147,
    type: "city",
    address: "辽宁省 | Liaoning Province | مقاطعة لياونينغ",
  },
  {
    name: "厦门",
    nameEn: "Xiamen",
    nameAr: "شيامن",
    nameMs: "Xiamen",
    namePt: "Xiamen",
    nameEs: "Xiamen",
    lat: 24.4798,
    lng: 118.0894,
    type: "city",
    address: "福建省 | Fujian Province | مقاطعة فوجيان",
  },

  // Beijing Landmarks
  {
    name: "天安门广场",
    nameEn: "Tiananmen Square",
    nameAr: "ميدان تيانانمن",
    nameMs: "Dataran Tiananmen",
    namePt: "Praça Tiananmen",
    nameEs: "Plaza de Tiananmén",
    lat: 39.9055,
    lng: 116.3976,
    type: "landmark",
    address: "北京市东城区 | Dongcheng, Beijing | دونغتشنغ، بكين",
  },
  {
    name: "故宫",
    nameEn: "Forbidden City",
    nameAr: "المدينة المحرمة",
    nameMs: "Kota Terlarang",
    namePt: "Cidade Proibida",
    nameEs: "Ciudad Prohibida",
    lat: 39.9163,
    lng: 116.3972,
    type: "landmark",
    address: "北京市东城区 | Dongcheng, Beijing | دونغتشنغ، بكين",
  },
  {
    name: "长城",
    nameEn: "Great Wall",
    nameAr: "سور الصين العظيم",
    nameMs: "Tembok Besar",
    namePt: "Grande Muralha",
    nameEs: "Gran Muralla",
    lat: 40.4319,
    lng: 116.5704,
    type: "landmark",
    address: "北京市延庆区 | Yanqing, Beijing | يانكينغ، بكين",
  },
  {
    name: "颐和园",
    nameEn: "Summer Palace",
    nameAr: "القصر الصيفي",
    nameMs: "Istana Musim Panas",
    namePt: "Palácio de Verão",
    nameEs: "Palacio de Verano",
    lat: 39.9998,
    lng: 116.2755,
    type: "landmark",
    address: "北京市海淀区 | Haidian, Beijing | هايديان، بكين",
  },
  {
    name: "天坛",
    nameEn: "Temple of Heaven",
    nameAr: "معبد السماء",
    nameMs: "Kuil Syurga",
    namePt: "Templo do Céu",
    nameEs: "Templo del Cielo",
    lat: 39.8826,
    lng: 116.4066,
    type: "landmark",
    address: "北京市东城区 | Dongcheng, Beijing | دونغتشنغ، بكين",
  },
  {
    name: "鸟巢",
    nameEn: "Bird's Nest",
    nameAr: "عش الطائر",
    nameMs: "Sarang Burung",
    namePt: "Ninho de Pássaro",
    nameEs: "Nido de Pájaro",
    lat: 39.9928,
    lng: 116.3903,
    type: "landmark",
    address: "北京市朝阳区 | Chaoyang, Beijing | تشاويانغ، بكين",
  },
  {
    name: "北京首都国际机场",
    nameEn: "Beijing Capital Airport",
    nameAr: "مطار بكين الدولي",
    nameMs: "Lapangan Terbang Beijing",
    namePt: "Aeroporto de Pequim",
    nameEs: "Aeropuerto de Pekín",
    lat: 40.0799,
    lng: 116.6031,
    type: "airport",
    address: "北京市顺义区 | Shunyi, Beijing | شونيي، بكين",
  },

  // Shanghai Landmarks
  {
    name: "东方明珠",
    nameEn: "Oriental Pearl Tower",
    nameAr: "برج اللؤلؤة الشرقية",
    nameMs: "Menara Mutiara Oriental",
    namePt: "Torre Pérola Oriental",
    nameEs: "Torre Perla Oriental",
    lat: 31.2397,
    lng: 121.4995,
    type: "landmark",
    address: "上海市浦东新区 | Pudong, Shanghai | بودونغ، شنغهاي",
  },
  {
    name: "外滩",
    nameEn: "The Bund",
    nameAr: "البوند",
    nameMs: "The Bund",
    namePt: "O Bund",
    nameEs: "El Bund",
    lat: 31.2408,
    lng: 121.4901,
    type: "landmark",
    address: "上海市黄浦区 | Huangpu, Shanghai | هوانغبو، شنغهاي",
  },
  {
    name: "上海迪士尼乐园",
    nameEn: "Shanghai Disneyland",
    nameAr: "ديزني لاند شنغهاي",
    nameMs: "Disneyland Shanghai",
    namePt: "Disneylândia de Xangai",
    nameEs: "Disneylandia de Shanghái",
    lat: 31.1434,
    lng: 121.6661,
    type: "landmark",
    address: "上海市浦东新区 | Pudong, Shanghai | بودونغ، شنغهاي",
  },
  {
    name: "南京路",
    nameEn: "Nanjing Road",
    nameAr: "طريق نانجينغ",
    nameMs: "Jalan Nanjing",
    namePt: "Rua Nanjing",
    nameEs: "Calle Nanjing",
    lat: 31.2354,
    lng: 121.4754,
    type: "landmark",
    address: "上海市黄浦区 | Huangpu, Shanghai | هوانغبو، شنغهاي",
  },
  {
    name: "上海浦东国际机场",
    nameEn: "Shanghai Pudong Airport",
    nameAr: "مطار شنغهاي بودونغ",
    nameMs: "Lapangan Terbang Pudong Shanghai",
    namePt: "Aeroporto de Pudong",
    nameEs: "Aeropuerto de Pudong",
    lat: 31.1443,
    lng: 121.8083,
    type: "airport",
    address: "上海市浦东新区 | Pudong, Shanghai | بودونغ، شنغهاي",
  },

  // Guangzhou & Shenzhen
  { name: "广州塔", nameEn: "Canton Tower", nameAr: "برج كانتون", lat: 23.1088, lng: 113.3191, type: "landmark" },
  {
    name: "深圳世界之窗",
    nameEn: "Window of the World",
    nameAr: "نافذة العالم",
    lat: 22.5374,
    lng: 113.9731,
    type: "landmark",
  },
  {
    name: "深圳欢乐谷",
    nameEn: "Happy Valley Shenzhen",
    nameAr: "وادي السعادة",
    lat: 22.5456,
    lng: 113.9841,
    type: "landmark",
  },

  // Hangzhou
  { name: "西湖", nameEn: "West Lake", nameAr: "البحيرة الغربية", lat: 30.2489, lng: 120.1356, type: "landmark" },
  { name: "雷峰塔", nameEn: "Leifeng Pagoda", nameAr: "باغودا ليفينغ", lat: 30.2315, lng: 120.1489, type: "landmark" },

  // Xi'an
  { name: "兵马俑", nameEn: "Terracotta Army", nameAr: "جيش الطين", lat: 34.3848, lng: 109.2785, type: "landmark" },
  {
    name: "西安城墙",
    nameEn: "Xi'an City Wall",
    nameAr: "سور مدينة شيان",
    lat: 34.2583,
    lng: 108.9286,
    type: "landmark",
  },

  // Chengdu
  {
    name: "成都大熊猫基地",
    nameEn: "Chengdu Panda Base",
    nameAr: "قاعدة الباندا",
    lat: 30.7317,
    lng: 104.1503,
    type: "landmark",
  },
  {
    name: "宽窄巷子",
    nameEn: "Kuanzhai Alley",
    nameAr: "زقاق كوانزهاي",
    lat: 30.6731,
    lng: 104.0522,
    type: "landmark",
  },

  // International Cities
  { name: "纽约", nameEn: "New York", nameAr: "نيويورك", lat: 40.7128, lng: -74.006, type: "city" },
  { name: "伦敦", nameEn: "London", nameAr: "لندن", lat: 51.5074, lng: -0.1278, type: "city" },
  { name: "巴黎", nameEn: "Paris", nameAr: "باريس", lat: 48.8566, lng: 2.3522, type: "city" },
  { name: "东京", nameEn: "Tokyo", nameAr: "طوكيو", lat: 35.6762, lng: 139.6503, type: "city" },
  { name: "悉尼", nameEn: "Sydney", nameAr: "سيدني", lat: -33.8688, lng: 151.2093, type: "city" },
  { name: "迪拜", nameEn: "Dubai", nameAr: "دبي", lat: 25.2048, lng: 55.2708, type: "city" },
  { name: "新加坡", nameEn: "Singapore", nameAr: "سنغافورة", lat: 1.3521, lng: 103.8198, type: "city" },

  // Famous International Landmarks
  {
    name: "自由女神像",
    nameEn: "Statue of Liberty",
    nameAr: "تمثال الحرية",
    lat: 40.6892,
    lng: -74.0445,
    type: "landmark",
  },
  { name: "埃菲尔铁塔", nameEn: "Eiffel Tower", nameAr: "برج إيفل", lat: 48.8584, lng: 2.2945, type: "landmark" },
  { name: "大本钟", nameEn: "Big Ben", nameAr: "بيغ بن", lat: 51.5007, lng: -0.1246, type: "landmark" },
  { name: "富士山", nameEn: "Mount Fuji", nameAr: "جبل فوجي", lat: 35.3606, lng: 138.7278, type: "landmark" },
  {
    name: "悉尼歌剧院",
    nameEn: "Sydney Opera House",
    nameAr: "دار أوبرا سيدني",
    lat: -33.8568,
    lng: 151.2153,
    type: "landmark",
  },
  { name: "哈利法塔", nameEn: "Burj Khalifa", nameAr: "برج خليفة", lat: 25.1972, lng: 55.2744, type: "landmark" },
]
